"projectile behavior"
XeroKimo/Delu-Bullet-Hell pull request #12
Opened 2023-05-17 13:14 UTC by Axetusk

This has the projectile behavior you wanted me to do. Everything should be commented and the demonstration is in the sample scene. If the idea is to fire downwards then it is easy to change.

2023-05-17 22:10 UTC, XeroKimo requested changes
I grabbed the project, and opened up your sample scene, and the bullet prefab is not pushed, so I can't test however way you've decided to set up the scene. 

Please also make the changes as requested, and reply to anything below if you have any questions

2023-05-17 22:10 UTC, XeroKimo commented on Assets/Delu Bullet Hell/Scripts/ProjectileBehavior.cs
> +            GetComponent<Rigidbody2D>().velocity = this.transform.up * bulletSpeed; //Move bullet up
Don't hard code the direction, actually give it a field that can be modified.

2023-05-17 22:10 UTC, XeroKimo commented on Assets/Delu Bullet Hell/Scripts/ProjectileBehavior.cs
> +        public GameObject bullet;
This bullet field shouldn't need to exist. The game object that this script is attached to is the bullet itself

2023-05-17 22:10 UTC, XeroKimo commented on Assets/Delu Bullet Hell/Scripts/ProjectileBehavior.cs
> +            Destroy(bullet); //Destroys bullet upon contact (feel free to delete if not needed)
For now just Destroy(gameObject) and not bullet due to one of the comments above

2023-05-18 22:37 UTC, Axetusk commented on Assets/Delu Bullet Hell/Scripts/ProjectileBehavior.cs
> +            GetComponent<Rigidbody2D>().velocity = this.transform.up * bulletSpeed; //Move bullet up
Fixed it up to now have a line that assigns the direction which to fire the bullet through a field that can be modified.

2023-05-18 22:38 UTC, Axetusk commented on Assets/Delu Bullet Hell/Scripts/ProjectileBehavior.cs
> +        public GameObject bullet;
Removed it and replaced with bulletRotation field

2023-05-18 22:38 UTC, Axetusk commented on Assets/Delu Bullet Hell/Scripts/ProjectileBehavior.cs
> +            Destroy(bullet); //Destroys bullet upon contact (feel free to delete if not needed)
Fixed

2023-05-19 23:02 UTC, XeroKimo approved these changes
You're free to commit this now into the experimental branch

2023-05-20 08:47 UTC, merged