"weapon arsenal script"
XeroKimo/Delu-Bullet-Hell pull request #17
Opened 2023-05-25 10:52 UTC by Axetusk

this should include a weapon arsenal script connected to the weapon scriptable object.

there is also a demonstration in the sample scene where it waits for 3 seconds before firing 5 bullets

2023-05-28 23:04 UTC, XeroKimo requested changes
Despite this not being fully within the specs, there are future plans that will change how this class will work, so after the requested changes, I'll accept as this will basically be a proof of concept anyways

2023-05-29 04:51 UTC, Axetusk commented on Assets/Delu Bullet Hell/Scripts/WeaponArsenal.cs
> +        private int bulletAmnt;
done, the example provided actually proved to be extremely useful and i thank you for that

2023-05-29 04:51 UTC, Axetusk commented on Assets/Delu Bullet Hell/Scripts/WeaponArsenal.cs
> +                bulletC.transform.position = savePos; //applies the current position to the bullet
fixed up the part you asked for

2023-05-29 18:03 UTC, XeroKimo approved these changes

2023-05-30 10:34 UTC, merged